# In this part we will be setting the parameters, reading the image and resizing it.

In [11]:
import cv2
import numpy as np

num_down = 2
num_bilateral = 7

img_rgb = cv2.imread("C:/Users/ARYAN/cartoon_python/rajaGanapathy.jpg")
print(img_rgb.shape)
img_rgb = cv2.resize(img_rgb,(800,800))

(995, 850, 3)


# Now, we will be downsampling the image and then applying bilateral filter, mentioned amount of times.

In [8]:
img_rgb=cv2.resize(img_rgb,(800,800))
img_color = img_rgb
for _ in range(num_down):
    img_color = cv2.pyrDown(img_color)
for _ in range(num_bilateral):
    img_color = cv2.bilateralFilter(img_color,5,9,9)

# We will now unsample, convert the image to grayscale and apply median blur. After that, apply thresholding.

In [9]:
for _ in range(num_down):
    img_color = cv2.pyrUp(img_color)

img_gray = cv2.cvtColor(img_rgb,cv2.COLOR_RGB2GRAY)
img_blur = cv2.medianBlur(img_gray, 7)

img_edge = cv2.adaptiveThreshold(img_blur, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 9, 2)
print(img_edge)

[[  0   0   0 ... 255 255 255]
 [  0   0   0 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]


# We now perform 'bitwise AND', and then display the resultant image. Do make sure to add in the end: cv2.waitkey(0)

In [10]:
img = cv2.cvtColor(img_edge, cv2.COLOR_GRAY2RGB)
img_cartoon = cv2.bitwise_and(img_color, img)
#cv2.imshow("cartoon",img_cartoon)
stack = np.hstack([img_rgb,img_cartoon])
cv2.imshow('Cartoonized image', stack)
cv2.waitKey(0) 
cv2.destroyAllWindows() 